apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acm-install-acs
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/SkylarScaling/acm-install-acs.git
    targetRevision: main
    path: .
    plugin:
      name: policy-generator
  destination:
    server: https://kubernetes.default.svc
    namespace: acm-install-policies
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 3m
